input {
  http {
    port => 5044
  }
}

filter {
  mysql {
    host => "your_mysql_host"
    username => "your_mysql_username"
    password => "your_mysql_password"
    database => "your_database"
    query => "SELECT * FROM your_table"
  }
}

output {
  stdout { codec => json }
}
